name: LevelReward
version: 1.0-SNAPSHOT
main: rindong.plugin.levelreward.levelreward.LevelReward
authors: [Rindong]
commands:
  levelreward:
    description: 主指令
permissions:
  levelreward.reload:
    description: 重载插件
    default: op